### ISSUE TITLE
peer.js 코드 좀 봐줄사람

### ISSUE THREAD

**Issue by whitepaper907** [whitepaper907/learni_test#30]
peer.js 코드 작성했는데, 한번 검토해줄사람

**Comment by hyoseung2000** [comment]
<리뷰내용>: LGTM 🔥
<수정제안코드>: ``


commented from Learniverse

**Comment by uujiinn** [comment]
<리뷰내용>: 잘 작성한 것 같은뎅?!
<수정제안코드>: ``


commented from Learniverse

**Comment by iamphj3** [comment]
<리뷰내용>: let은 초기화 안해도 되지 않아?
<수정제안코드>: `    let consumer;`


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 여기부분 수정해야될 것 같은데
<수정제안코드>: `    this.memberId = member;`


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 이거 삭제해도 될 것 같은데?
<수정제안코드>: `//`


commented from Learniverse

**Comment by uujiinn** [comment]
<리뷰내용>: 코멘트
코멘트
<수정제안코드>: ``


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 여기서 리턴하는거 아니지 않아?
<수정제안코드>: `//`


commented from Learniverse

**Comment by uujiinn** [comment]
<리뷰내용>: 여기 수정해보장
<수정제안코드>: `addTransport(transport){
    this.transports.set(transport.id, transport); //사실 수정된거 없음
}`


commented from Learniverse

**Comment by uujiinn** [comment]
<리뷰내용>: 이거 추가해보장
<수정제안코드>: `  removeConsumer(consumer_id) {
    this.consumers.delete(consumer_id);//추가
  }`


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 이거 맞는지 확인해볼래??
<수정제안코드>: `export default Peers; `


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 여기 !!
<수정제안코드>: `//`


commented from Learniverse
