### ISSUE TITLE
redis랑 연동한 코드 

### ISSUE THREAD

**Issue by whitepaper907** [whitepaper907/learni_test#34]
이거 redis랑 연동한건데 뭔가 잘 안되네,,,

**Comment by whitepaper907** [comment]
<리뷰내용>: 이거 일단 주석할거면 삭제하는게 좋은듯?
<수정제안코드>: `//`


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 이거 맞아??? 이거는 없어도 될 것 같은데...
<수정제안코드>: ``


commented from Learniverse

**Comment by iamphj3** [comment]
<리뷰내용>: 이 코드는 뭐야??
<수정제안코드>: ``


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 아 이거 stock server 랑 redis 연결한거 추가한거야!!
<수정제안코드>: ``


commented from Learniverse

**Comment by iamphj3** [comment]
<리뷰내용>: 디버깅용 코드 일단 남겨놓자!!
<수정제안코드>: `console.log(memberWithScore);`


commented from Learniverse

**Comment by hyoseung2000** [comment]
<리뷰내용>: 이렇게 해보는거 어때?
<수정제안코드>: `//result awit로 안해도 될 것 같아`


commented from Learniverse

**Comment by uujiinn** [comment]
<리뷰내용>: 나는 좋은것같앙
LGTM!!
<수정제안코드>: ``


commented from Learniverse

**Comment by iamphj3** [comment]
<리뷰내용>: 여기도 이렇게 수정하자!
<수정제안코드>: `console.log(key, score);
console.log(value);`


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 이거 수정하자
<수정제안코드>: ``


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 아냐 이렇게 하자
<수정제안코드>: ``


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 이렇게!
<수정제안코드>: `export addOutstanding = async (userId, historyId) => {`


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 이렇게 해봐
<수정제안코드>: `console.log(streamclient);`


commented from Learniverse

**Comment by whitepaper907** [comment]
<리뷰내용>: 이렇게 해봐
<수정제안코드>: `console.log(sellclient);`


commented from Learniverse
